### ISSUE TITLE
Double ABout

### ISSUE THREAD

**Issue by Voltern** [VutonDesign/vutondesign.github.io#10]
![bnb](https://user-images.githubusercontent.com/33236873/32408112-0aba654e-c169-11e7-9756-6b3d95ba895b.png)

**Comment by Voltern** [comment]
#11

**Comment by VutonDesign** [comment]
Thanks for this, I'll get to it quickly.

**Comment by Voltern** [comment]
I Can Fix it.

**Comment by VutonDesign** [comment]
It's already fixed, Thanks for reporting it. 👍
