### ISSUE TITLE
Use cloudflare for https?

### ISSUE THREAD

**Issue by ateesdalejr** [vutondesign/vutondesign.github.io#16]
You can use [this](https://www.jonathan-petitcolas.com/2017/01/13/using-https-with-custom-domain-name-on-github-pages.html) guide if you'd like or just search `HTTPS with github pages and cloudflare`. Anyways good luck. Cloudflare's free so, I use it for my domains as well.

**Comment by vutondesign** [comment]
I didn't know that was possible with Github pages, I'll look into setting that up. Thanks 😄

**Comment by vutondesign** [comment]
@ateesdalejr Thank you for sending me that guide, I've changed nameservers & setup page rules so I should be up and running with HTTPS tomorrow.
