### ISSUE TITLE
Can I get my site linked?

### ISSUE THREAD

**Issue by 2aezlo** [vutondesign/vutondesign.github.io#19]
- [ ] 
****
# 
## 
###
__

> 
``
[](url)

**Comment by vutondesign** [comment]
Please read over this - https://github.com/vutondesign/vutondesign.github.io/blob/master/site-linking-info.md

**Comment by vutondesign** [comment]
ping @2aezlo

**Comment by 2aezlo** [comment]
You can see your site mentioned [here](//athelo.net/links)

**Comment by vutondesign** [comment]
Great, I'll add yours right now!

**Comment by vutondesign** [comment]
Done, your site is linked at - https://vutondesign.com/links.html
