### ISSUE TITLE
JS test button

### ISSUE THREAD

**Issue by DatOneLefty** [VutonDesign/vutondesign.github.io#2]
I can put in any word I want 

"Wow! I love the number you hate too!"

(oh and also add some more margins n stuff)

**Comment by VutonDesign** [comment]
@DatOneLefty Thank's for bringing that up, I'll get that it in a few days. The site is also about to be re-designed so it will look better after that.

**Comment by DatOneLefty** [comment]
i recommend closing the issue after it is completed, it helps keep stuff organized, i dont see the changes on the site if you did them (might be cached)

**Comment by VutonDesign** [comment]
I've closed it as the whole site is getting redesigned right now. I'm moving a new version of that JavaScript test to a new page.

**Comment by DatOneLefty** [comment]
ah ok
