### ISSUE TITLE
index.html in Javascript

### ISSUE THREAD

**Issue by GreenBayRules** [VutonDesign/vutondesign.github.io#3]
Why did you put an HTML file in the JS folder xD

**Comment by VutonDesign** [comment]
It's the js page folder 😆

**Comment by GreenBayRules** [comment]
Well yeah but you should make a separate file called "index.js" put that in the JS folder and then inject that into the index.html.

**Comment by VutonDesign** [comment]
This is becoming my old site soon anyway so...

**Comment by GreenBayRules** [comment]
oh wheres the new site. lol I love making random issues in peoples stuff :P

**Comment by VutonDesign** [comment]
It's test-site2

**Comment by GreenBayRules** [comment]
okay.
