### ISSUE TITLE
Question: Can i use your css with credit?

### ISSUE THREAD

**Issue by Voltern** [VutonDesign/vutondesign.github.io#4]

**Comment by Hexsphere** [comment]
If you need to copy his CSS, then you really need to look up how to code websites....

**Comment by Voltern** [comment]
i know how to code websites.
I Just like the theme.

**Comment by VutonDesign** [comment]
Depending on how much code you want to use, But since you've just ignored @Hexsphere and copied it already, I'd rather you didn't use it.

Please take down the code you've already copied.

**Comment by Voltern** [comment]
?

**Comment by VutonDesign** [comment]
?
